# Generated by Django 3.0.8 on 2020-07-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kampania_redlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kampanii', models.CharField(max_length=100)),
                ('redlink_id_a_sitek_pl', models.CharField(max_length=100)),
                ('redlink_id_c_idziak_pl', models.CharField(max_length=100)),
                ('redlink_id_i_rosinska_pl', models.CharField(max_length=100)),
                ('redlink_id_m_mikolajczyk_pl', models.CharField(max_length=100)),
                ('redlink_id_m_kluszczynska_pl', models.CharField(max_length=100)),
                ('redlink_id_t_piszczola_pl', models.CharField(max_length=100)),
                ('redlink_id_a_biegajlo_en', models.CharField(max_length=100)),
                ('redlink_id_j_nieglos_en', models.CharField(max_length=100)),
                ('redlink_id_l_urbanczyk_en', models.CharField(max_length=100)),
                ('redlink_id_m_prange_en', models.CharField(max_length=100)),
                ('redlink_id_m_bujakowska_en', models.CharField(max_length=100)),
                ('redlink_id_p_strzelecki_en', models.CharField(max_length=100)),
                ('redlink_id_l_urbanczyk_de', models.CharField(max_length=100)),
                ('redlink_id_m_prange_de', models.CharField(max_length=100)),
                ('redlink_id_m_bujakowska_de', models.CharField(max_length=100)),
                ('redlink_id_a_biegajlo_fr', models.CharField(max_length=100)),
                ('redlink_id_m_prange_fr', models.CharField(max_length=100)),
            ],
        ),
    ]
