# Generated by Django 3.0.8 on 2020-07-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowy_mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampania_redlink',
            name='redlink_id_m_sobaszek_it',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
