# Generated by Django 3.0.8 on 2020-07-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowy_mailing', '0002_kampania_redlink_redlink_id_m_sobaszek_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampania_redlink',
            name='kiedy_wyslany',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
