# Generated by Django 3.0.8 on 2020-07-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowy_mailing', '0003_kampania_redlink_kiedy_wyslany'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampania_redlink',
            name='temat_mailingu_de',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kampania_redlink',
            name='temat_mailingu_en',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kampania_redlink',
            name='temat_mailingu_fr',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kampania_redlink',
            name='temat_mailingu_pl',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
