# Generated by Django 3.0.8 on 2020-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowy_mailing', '0004_auto_20200721_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampania_redlink',
            name='link_content',
            field=models.CharField(default='Nie podany', max_length=200),
            preserve_default=False,
        ),
    ]
