# Generated by Django 3.0.8 on 2020-07-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nowy_mailing', '0005_kampania_redlink_link_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kampania_redlink',
            old_name='redlink_id_m_sobaszek_it',
            new_name='redlink_id_m_sobaszek_en',
        ),
    ]
